In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\Dell\Youtube_Analysis\ytcleaned')
df

Unnamed: 0     video_id trending_date  \
0               0  2kyS6SvSYSE    2017-11-14   
1               1  1ZAPwfrtAFY    2017-11-14   
2               2  5qpjK5DgCt4    2017-11-14   
3               3  puqaWrEC7tY    2017-11-14   
4               4  d380meD0W0M    2017-11-14   
...           ...          ...           ...   
40944       40944  BZt0qjTWNhw    2018-06-14   
40945       40945  1h7KV2sjUWY    2018-06-14   
40946       40946  D6Oy4LfoqsU    2018-06-14   
40947       40947  oV0zkMe1K8s    2018-06-14   
40948       40948  ooyjaVdt-jA    2018-06-14   

                                                   title  \
0                     WE WANT TO TALK ABOUT OUR MARRIAGE   
1      The Trump Presidency: Last Week Tonight with J...   
2      Racist Superman | Rudy Mancuso, King Bach & Le...   
3                       Nickelback Lyrics: Real or Fake?   
4                               I Dare You: GOING BALD!?   
...                                                  ...   
40944                       The Cat Who Caught the Laser   
40945                         True Facts : Ant Mutualism   
40946  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...   
40947                How Black Panther Should Have Ended   
40948  Official Call of Duty®: Black Ops 4 — Multipla...   

                  channel_title  category_id               publish_time  \
0                  CaseyNeistat           22  2017-11-13 17:13:01+00:00   
1               LastWeekTonight           24  2017-11-13 07:30:00+00:00   
2                  Rudy Mancuso           23  2017-11-12 19:05:24+00:00   
3         Good Mythical Morning           24  2017-11-13 11:00:04+00:00   
4                      nigahiga           24  2017-11-12 18:01:41+00:00   
...                         ...          ...                        ...   
40944             AaronsAnimals           15  2018-05-18 13:00:04+00:00   
40945                  zefrank1           22  2018-05-18 01:00:06+00:00   
40946                Brad Mondo           24  2018-05-18 17:34:22+00:00   
40947  How It Should Have Ended            1  2018-05-17 17:00:04+00:00   
40948              Call of Duty           20  2018-05-17 17:09:38+00:00   

          views   likes  dislikes  comment_count  comments_disabled  \
0        748374   57527      2966          15954              False   
1       2418783   97185      6146          12703              False   
2       3191434  146033      5339           8181              False   
3        343168   10172       666           2146              False   
4       2095731  132235      1989          17518              False   
...         ...     ...       ...            ...                ...   
40944   1685609   38160      1385           2657              False   
40945   1064798   60008       382           3936              False   
40946   1066451   48068      1032           3992              False   
40947   5660813  192957      2846          13088              False   
40948  10306119  357079    212976         144795              False   

       ratings_disabled  video_error_or_removed             Genre  
0                 False                   False    People & Blogs  
1                 False                   False     Entertainment  
2                 False                   False            Comedy  
3                 False                   False     Entertainment  
4                 False                   False     Entertainment  
...                 ...                     ...               ...  
40944             False                   False    Pets & Animals  
40945             False                   False    People & Blogs  
40946             False                   False     Entertainment  
40947             False                   False  Film & Animation  
40948             False                   False            Gaming  

[40949 rows x 15 columns]

In [41]:
genre_dict = df['Genre'].to_dict()

In [22]:
df.drop(columns = ['Unnamed: 0', 'video_id', 'publish_time', 'trending_date'], axis = 1, inplace = True)

In [23]:
df.head(2)

title    channel_title  \
0                 WE WANT TO TALK ABOUT OUR MARRIAGE     CaseyNeistat   
1  The Trump Presidency: Last Week Tonight with J...  LastWeekTonight   

   category_id    views  likes  dislikes  comment_count  comments_disabled  \
0           22   748374  57527      2966          15954              False   
1           24  2418783  97185      6146          12703              False   

   ratings_disabled  video_error_or_removed           Genre  
0             False                   False  People & Blogs  
1             False                   False   Entertainment

In [25]:
df.isnull().sum()

title                     0
channel_title             0
category_id               0
views                     0
likes                     0
dislikes                  0
comment_count             0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
Genre                     0
dtype: int64

In [24]:
for i in df.columns:
    print(df[i].nunique())

6455
2207
16
40478
29850
8516
13773
2
2
2
16


In [26]:
for i in df.columns:
    print(df[i].unique())

['WE WANT TO TALK ABOUT OUR MARRIAGE'
 'The Trump Presidency: Last Week Tonight with John Oliver (HBO)'
 'Racist Superman | Rudy Mancuso, King Bach & Lele Pons' ...
 'Drop the Mic w/ Ashton Kutcher & Sean Diddy Combs'
 'Carla Makes BA Smashburgers | From the Test Kitchen | Bon Appétit'
 'Katherine Langford on 13 Reasons Why, Australia & Doctor Parents']
['CaseyNeistat' 'LastWeekTonight' 'Rudy Mancuso' ... 'All Def Digital'
 'How It Should Have Ended' 'Ubisoft North America']
[22 24 23 28  1 25 17 10 15 27 26  2 19 20 29 43]
[  748374  2418783  3191434 ...  1066451  5660813 10306119]
[ 57527  97185 146033 ...  48068 192957 357079]
[  2966   6146   5339 ...  42833   4166 212976]
[ 15954  12703   8181 ...  52432  62610 144795]
[False  True]
[False  True]
[False  True]
['People & Blogs' 'Entertainment' 'Comedy' 'Science & Technology'
 'Film & Animation' 'News & Politics' 'Sports' 'Music' 'Pets & Animals'
 'Education' 'Howto & Style' 'Autos & Vehicles' 'Travel & Events' 'Gaming'
 'Nonprofit

In [44]:

'''import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20,10))
sns.heatmap(df.corr(),annot=True)
plt.show()'''

'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nplt.figure(figsize=(20,10))\nsns.heatmap(df.corr(),annot=True)\nplt.show()'

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['comments_disabled'] = le.fit_transform(df['comments_disabled'])
df['comments_disabled'].unique()

array([0, 1], dtype=int64)

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['ratings_disabled'] = le.fit_transform(df['ratings_disabled'])
df['ratings_disabled'].unique()

array([0, 1], dtype=int64)

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['video_error_or_removed'] = le.fit_transform(df['video_error_or_removed'])
df['video_error_or_removed'].unique()

array([0, 1], dtype=int64)

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])
df['Genre'].unique()

array([10,  3,  1, 12,  4,  8, 14,  7, 11,  2,  6,  0, 15,  5,  9, 13])

In [32]:
df

title  \
0                     WE WANT TO TALK ABOUT OUR MARRIAGE   
1      The Trump Presidency: Last Week Tonight with J...   
2      Racist Superman | Rudy Mancuso, King Bach & Le...   
3                       Nickelback Lyrics: Real or Fake?   
4                               I Dare You: GOING BALD!?   
...                                                  ...   
40944                       The Cat Who Caught the Laser   
40945                         True Facts : Ant Mutualism   
40946  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...   
40947                How Black Panther Should Have Ended   
40948  Official Call of Duty®: Black Ops 4 — Multipla...   

                  channel_title  category_id     views   likes  dislikes  \
0                  CaseyNeistat           22    748374   57527      2966   
1               LastWeekTonight           24   2418783   97185      6146   
2                  Rudy Mancuso           23   3191434  146033      5339   
3         Good Mythical Morning           24    343168   10172       666   
4                      nigahiga           24   2095731  132235      1989   
...                         ...          ...       ...     ...       ...   
40944             AaronsAnimals           15   1685609   38160      1385   
40945                  zefrank1           22   1064798   60008       382   
40946                Brad Mondo           24   1066451   48068      1032   
40947  How It Should Have Ended            1   5660813  192957      2846   
40948              Call of Duty           20  10306119  357079    212976   

       comment_count  comments_disabled  ratings_disabled  \
0              15954                  0                 0   
1              12703                  0                 0   
2               8181                  0                 0   
3               2146                  0                 0   
4              17518                  0                 0   
...              ...                ...               ...   
40944           2657                  0                 0   
40945           3936                  0                 0   
40946           3992                  0                 0   
40947          13088                  0                 0   
40948         144795                  0                 0   

       video_error_or_removed  Genre  
0                           0     10  
1                           0      3  
2                           0      1  
3                           0      3  
4                           0      3  
...                       ...    ...  
40944                       0     11  
40945                       0     10  
40946                       0      3  
40947                       0      4  
40948                       0      5  

[40949 rows x 11 columns]

In [45]:
x = df[['views','dislikes','comment_count','Genre']]

In [46]:
x

views  dislikes  comment_count  Genre
0        748374      2966          15954     10
1       2418783      6146          12703      3
2       3191434      5339           8181      1
3        343168       666           2146      3
4       2095731      1989          17518      3
...         ...       ...            ...    ...
40944   1685609      1385           2657     11
40945   1064798       382           3936     10
40946   1066451      1032           3992      3
40947   5660813      2846          13088      4
40948  10306119    212976         144795      5

[40949 rows x 4 columns]

In [47]:
y = df['likes']

In [48]:
y

0         57527
1         97185
2        146033
3         10172
4        132235
          ...  
40944     38160
40945     60008
40946     48068
40947    192957
40948    357079
Name: likes, Length: 40949, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [50]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [54]:
from sklearn.metrics import accuracy_score

var = lr.score(x_test, y_test)
var

0.8922152486433544

In [55]:
bias = lr.score(x_train, y_train)
bias

0.8799235554046407

In [52]:
y_pred = lr.predict(x_test)
y_pred

array([ 52383.05813384, 391165.79477563, 113897.80779622, ...,
        11011.13210997,  84747.77310881,  57066.76206326])

In [59]:
import pickle
with open('model.pickle', 'wb') as model_file:           # wb is for we are storing the data in binary code
    pickle.dump(lr, model_file)           # dumping the model to the file

In [60]:
with open("model.pickle","rb") as mod:
    model = pickle.load(mod)

In [61]:
x_test.columns

Index(['views', 'dislikes', 'comment_count', 'Genre'], dtype='object')

In [62]:
model.predict([[86980, 4567, 489, 5]])

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([954.62863089])